version: '3.1'

services:
  kafka1:
    image: icorrea:kafka-zookeeper-less
    hostname: kafka1
    restart: always
    networks:
      kafka-net:
        ipv4_address: 172.21.0.5
    ports:
      - 9092:9092
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://172.21.0.5:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      PROCESS_ROLES: broker,controller
      CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093

networks:
  kafka-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24

